### ISSUE TITLE
Feature: User can view cryptocurrency details

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/crypto-catalog#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of the searched cryptocurrency

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will input text into the search bar and click submit, from there the detail view will appear with data on the requested cryptocurrency.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-11-14 181950](https://user-images.githubusercontent.com/113570457/201810674-1b843993-7cd7-4bbb-a75f-c39f807b89f7.png)

![Screenshot 2022-11-14 160311](https://user-images.githubusercontent.com/113570457/201793564-b49e901e-b704-4ae3-b086-b549e02ead88.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create header that will be present in every view.
- [x] Add a div [data-view="search"] to the HTML.
- [x] Create all the HTML and CSS necessary for the search view.
- [x] Make search input required.
- [x] Add a div [data-view="details"] to the HTML.
- [x] Create all the HTML and CSS necessary for the details view.
- [x] Create getCryptoData function to make a request to API to get data for user's search input by crypto name which will correlate with the API's 'id' property. 
- [x] Listen for 'submit' event on the search button to populate details view by using .textContent method to change text of the elements to match the wanted values in the response received once 'load' event fires from your getCryptoData function.
- [x] User can click on search anchor in header to return to search-view.
- [x] Show details view when a valid input is submitted
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
