### ISSUE TITLE
Feature: User can add cryptocurrency to watchlist

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/crypto-catalog#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add specific cryptocurrencies with their properties to their ‘watch list’.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After searching, the user will have an add button available to add any cryptocurrency they are looking at to their watchlist. If they choose to add it will take them to their watchlist view and show added cryptocurrency.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot 2022-11-15 145846](https://user-images.githubusercontent.com/113570457/202042590-c0865a4b-d800-41c2-a7f1-b4e7a713ffd2.png)

![Screenshot 2022-11-15 145707](https://user-images.githubusercontent.com/113570457/202042460-f282b174-3b8c-474e-9ab4-583539ccfd75.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add list property to data model and assign the value to an empty array so that you can push the added cryptos into there and deal with local storage.
- [x] Create button for user to press in order to add crypto currency in detail view to data model and local storage.
- [x] Listen for click events on the add button to add object to local storage.
- [x] Verify that each cryptocurrency the user chooses to add is saved in local storage on page reload.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
