### ISSUE TITLE
Feature: User can view their watchlist

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/crypto-catalog#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their watchlist after all their additions.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will have a button on the homepage named watchlist. Once pressed this will redirect the user to the watchlist view.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-11-14 161241](https://user-images.githubusercontent.com/113570457/201794504-e1cbf821-1cc7-4f84-a1df-c7b64ee65b66.png)
![Screenshot 2022-11-14 161216](https://user-images.githubusercontent.com/113570457/201794512-4e44a682-90dc-4670-9f41-ff8e363823ab.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling div[data-view="watchlist"] to HMTL.
- [x] Complete the necessary CSS and HTML for watchlist view.
- [x] Add some dummy entries to make sure it looks good.
- [x] Define a function that takes a single returned object from the API and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the 'DOMContentLoaded' event is fired.
- [x] When a user adds a coin to the watchlist, ensure that the view switches to watchlist and data-view property of data model is updated to 'watchlist'.
- [x] Make an anchor link that swaps to watchlist view, and updates data model data-view to 'watch-list' as well.
- [x] Create a click listener on either the whole list of items, or one individual list item that allows the user to return to detailed view of the cryptocurrency they've clicked on.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
