### ISSUE TITLE
Feature: User can delete cryptocurrencies from their watchlist

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/crypto-catalog#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete cryptocurrencies they no longer wish to have in their watchlist.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the watchlist, each list item will have an x that if clicked gives you the option to remove the cryptocurrency. Deleting it returns the user to the updated watchlist view.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot 2022-11-14 161718](https://user-images.githubusercontent.com/113570457/201795040-2e8e19d9-0b41-4647-8fa7-31e2d7298e05.png)

![Screenshot 2022-11-14 161835](https://user-images.githubusercontent.com/113570457/201795166-398ff4ac-f478-4f82-8a16-de16d44dcf2c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click target for deleting a list item on the watchlist view.
- [x] Show a confirmation modal when the user clicks the Delete List Item click target.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [x] Show the watchlist view if the user clicks Delete.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
