### ISSUE TITLE
Feature: User can view their current net worth

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/crypto-catalog#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their net worth across all cryptocurrency owned.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the watchlist view the user will have an option to input an amount of coins owned, that will then be multiplied by the current price of the asset. All assets will be added up and return a net worth.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-11-14 162123](https://user-images.githubusercontent.com/113570457/201795578-79fd0fb5-5942-4908-ad1a-e86bc1d7abf0.png)

![Screenshot 2022-11-14 162105](https://user-images.githubusercontent.com/113570457/201795588-e0f75a6a-c48c-4151-b264-b845050c28da.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a paragraph or header element at the top of watchlist view, above the unordered list for your calculated current net worth from the totalNetWorth variable you will create.
- [x] Add the necessary elements for coins owned to your dom creation function. This should include a form element, label for coins owned, an input element, a submit button for the input element, as well as an edit button that only appears once an input has been submitted. Edit button should be hidden in the beginning.
- [x] Once an input is put in and submitted, show watchlist view with input value, hide submit button, and show edit button.
- [x] Loop over the existing items in your data.list array.
- [x] Create a variable called totalNetWorth and initalize it to 0.
- [x] Use the input in coins owned and multiply that by the coins current_price, add it to totalNetWorth and reassign the value.
- [x] Have the function return totalNetWorth and use that value in your element for the first step.
- [x] When edit button is clicked, make data.editing that objects id. 
- [x] When edit button is clicked clear the text input and make the user focus on it.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
